### ISSUE TITLE
Wrong > Symbol

### ISSUE THREAD

**Issue by FelixLttks** [igorovh/twitch-enhancer#60]
Right under the streamer's name, where it says 'watchtime,' shouldn't '>' be replaced by '<?
![image](https://github.com/igorovh/twitch-enhancer/assets/76926119/fb008630-c1dc-4da6-859b-72d490865f5d)

'<' is the 'less than' operator, which fits better here.

"watchtime less than 1min"

**Comment by igorovh** [comment]
changed [here](https://github.com/igorovh/twitch-enhancer/commit/4a1831b111fbe5a4a5c17b581c38a890583af4bb#diff-7a6acb6133e4f23425d71f74b041b26dfd06b1f7211e0178420374026592811bR60)
